### ISSUE TITLE
Zmiana sposobu zwracania list z serwisów

### ISSUE THREAD

**Issue by Olin44** [bulamen7/shoooop#1]
https://github.com/bulamen7/shoooop/blob/7ce8f3dd397d9c4c21cdfedc770a0c0a8b4db98b/src/main/java/com/bulamen7/shop/service/order/OrderService.java#L33

Jeśli dane lecą bezpośrednio do frontu i nie chcesz żeby ci ktoś je zepsuł to powinieneś zwracać niemodyfikowalną listę. 

https://www.baeldung.com/java-stream-immutable-collection

Ogólnie zawsze lepiej zwracać niemodyfikowalną listę.

**Comment by Olin44** [comment]
Do poprawy tu i we wszystkich innych miejsach.

**Comment by bulamen7** [comment]
zrobione.
